//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easysave.Assets.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easysave.Assets.Ressources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différentielle.
        /// </summary>
        public static string diff {
            get {
                return ResourceManager.GetString("diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir.
        /// </summary>
        public static string explorer {
            get {
                return ResourceManager.GetString("explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complètes.
        /// </summary>
        public static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers cryptés.
        /// </summary>
        public static string homepage_encryptedstat {
            get {
                return ResourceManager.GetString("homepage_encryptedstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Stockés.
        /// </summary>
        public static string homepage_gostat {
            get {
                return ResourceManager.GetString("homepage_gostat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string homepage_name {
            get {
                return ResourceManager.GetString("homepage_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegardes.
        /// </summary>
        public static string homepage_savestat {
            get {
                return ResourceManager.GetString("homepage_savestat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string savepage_create {
            get {
                return ResourceManager.GetString("savepage_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une sauvegarde.
        /// </summary>
        public static string savepage_createtitle {
            get {
                return ResourceManager.GetString("savepage_createtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers pour.
        /// </summary>
        public static string savepage_files {
            get {
                return ResourceManager.GetString("savepage_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes les sauvegardes.
        /// </summary>
        public static string savepage_name {
            get {
                return ResourceManager.GetString("savepage_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la sauvegarde.
        /// </summary>
        public static string savepage_savename {
            get {
                return ResourceManager.GetString("savepage_savename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de sauvegarde.
        /// </summary>
        public static string savepage_savetype {
            get {
                return ResourceManager.GetString("savepage_savetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement du fichier source.
        /// </summary>
        public static string savepage_sourcedir {
            get {
                return ResourceManager.GetString("savepage_sourcedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier source : .
        /// </summary>
        public static string savepage_sourcefile {
            get {
                return ResourceManager.GetString("savepage_sourcefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logiciel métier (Nom du logiciel).
        /// </summary>
        public static string settings_blockingapp {
            get {
                return ResourceManager.GetString("settings_blockingapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types de fichiers a crypter.
        /// </summary>
        public static string settings_encryptable {
            get {
                return ResourceManager.GetString("settings_encryptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types de fichiers à ignorer lors d&apos;une sauvegarde.
        /// </summary>
        public static string settings_ignored {
            get {
                return ResourceManager.GetString("settings_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue de l&apos;application.
        /// </summary>
        public static string settings_lang {
            get {
                return ResourceManager.GetString("settings_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement des logs.
        /// </summary>
        public static string settings_logsdir {
            get {
                return ResourceManager.GetString("settings_logsdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types des logs.
        /// </summary>
        public static string settings_logstype {
            get {
                return ResourceManager.GetString("settings_logstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string settings_name {
            get {
                return ResourceManager.GetString("settings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers prioritaires (Dans l&apos;ordre de prioriteeeeeee).
        /// </summary>
        public static string settings_priority {
            get {
                return ResourceManager.GetString("settings_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string settings_save {
            get {
                return ResourceManager.GetString("settings_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement des sauvegardes.
        /// </summary>
        public static string settings_savedir {
            get {
                return ResourceManager.GetString("settings_savedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille limite des fichiers (Mo).
        /// </summary>
        public static string settings_sizelimit {
            get {
                return ResourceManager.GetString("settings_sizelimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue de l&apos;application.
        /// </summary>
        public static string welcome_lang {
            get {
                return ResourceManager.GetString("welcome_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement des logs.
        /// </summary>
        public static string welcome_logsdir {
            get {
                return ResourceManager.GetString("welcome_logsdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types des logs.
        /// </summary>
        public static string welcome_logstype {
            get {
                return ResourceManager.GetString("welcome_logstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement des sauvegardes.
        /// </summary>
        public static string welcome_savedir {
            get {
                return ResourceManager.GetString("welcome_savedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer.
        /// </summary>
        public static string welcome_start {
            get {
                return ResourceManager.GetString("welcome_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez procéder au paramètrage initial de l&apos;application avant de continuer.
        /// </summary>
        public static string welcome_subtitle {
            get {
                return ResourceManager.GetString("welcome_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci d&apos;avoir téléchargé EasySave by ProSoft.
        /// </summary>
        public static string welcome_title {
            get {
                return ResourceManager.GetString("welcome_title", resourceCulture);
            }
        }
    }
}
